version: '2'

services:
  app:
    image: 'featurespitter:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports: 
      - 8090:8090
    restart: always    
         
  client:
      image: 'client:latest'
      build:
        context : ./client/.
      container_name: client  
      ports: 
        - 8082:8080  
      depends_on:
         - app  
          
  db:
    image: 'postgres:13.1-alpine'
    restart: always
    ports: 
      - 5432:5432
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password